"""add status to jobs

Revision ID: 7daa051f6aad
Revises: f11d3bfe9e48
Create Date: 2026-10-04 20:30:42.728958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7daa051f6aad'
down_revision: Union[str, Sequence[str], None] = 'f11d3bfe9e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('status', sa.String(), nullable=True))



def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('jobs', 'status')

